blank_issues_enabled: true
contact_links:
  - name: Dev builds
    url: https://ci.viaversion.com/
    about: Before reporting a bug, please check if using master/dev builds from our ci fixes your issue.
